[package]
name = "simple"
version = "0.1.0"

[dependencies]
serde =  { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
json_schema_parser = { git = "https://github.com/wvdveer/json_schema_parser" }
